### ISSUE TITLE
Roadmap for initial data management

### ISSUE THREAD

**Issue by CasperWA** [M-ERA-NET-MEDIATE/admin#1]
### Store data

- [x] Parser [(basic) ](https://github.com/M-ERA-NET-MEDIATE/sofc-performance-datamanagement/tree/basic-parsing/sofc_performance_parser). @sygout 
- [x] Upload functionality to MongoDB (done by Daniel). There's an open PR: SINTEF/dlite#485 @CasperWA (review and "push")

### Get data

- [x] Query functionality to MongoDB (pure Python implementation - for now). @CasperWA 
- [x] Instantiate (in DLite) and present returned results from MongoDB (should be ported to OTE in the future) @CasperWA 
  - Questions regarding matching up with (locally) cached DLite instances that are the same, or same UUID but different content.

### Use data

- [ ] Simple plotter for any couple (two) properties, x,y-plot (probably matplotlib, bokeh, plotly...) @ajeklund 
- [ ] Generate input for further calculations. @sygout 
  - As a test: compute the volume of the channel and try to compute something "easy" based on the values we have.
- [ ] Get a set of standard use cases to use throughout the technology development. @didrikrs and @sygout 
  - [ ] Ask Salim and Thomas (LIST and Dresden) for varying degrees of advanced use cases.
  - [ ] Create list of tasks to solve/handle these use cases.

### Misc.

CRUD functionality (Create, Read, Update, Delete) for MongoDB - done by Daniel.
