### ISSUE TITLE
Roadmap for (initial) semantic data management

### ISSUE THREAD

**Issue by CasperWA** [M-ERA-NET-MEDIATE/admin#2]
Expand metadata and thereby data functionality

### Create ontology

- [ ] Create initial EMMO-based SOFC/SOEC domain ontology. @didrikrs 
- [ ] Add EMMO and initial SOFC/SOEC domain ontology to GraphDB. @CasperWA 
- [ ] Documentation for GraphDB exploration @ajeklund 
  - Should be at level for non-programmers.

### Map data models

- [ ] Add simple ontology mapping to models/entities (e.g., "volume", and similar). Using the Data perspective of EMMO??? Get help from Francesca and/or Jesper. @didrikrs + jesper and/or francesca
- [ ] Add more explicit and descriptive mappings. @didrikrs
